# Price Oscillations

```{r}
dPrice <-
  data %>%
    filter(scenario != "historical") %>%
    filter(str_starts(variable, "Price")) %>%
    filter(period >= 2010) %>% # 2005 values are invalid
    droplevels()
varsPE <-
  levels(dPrice$variable) %>%
  str_subset("^Price\\|Primary Energy\\|") %>%
  str_subset("\\|Moving Avg$", negate = TRUE)
varsSE <-
  levels(dPrice$variable) %>%
  str_subset("^Price\\|Secondary Energy\\|") %>%
  str_subset("\\|Moving Avg$", negate = TRUE)
varsFE <- 
  levels(dPrice$variable) %>%
  str_subset("^Price\\|Final Energy\\|") %>%
  str_subset(
    "\\|Moving Avg|\\|Total LCOE|\\|Fuel Cost|\\|Transport and Distribution|\\|Carbon Price Component|\\|Other Taxes$",
    negate = TRUE)
```


## Relative Variation

```{r}
relativeVariation <- function(v, p=seq_along(v)) {
  sum(abs(diff(v))) / (max(v) - min(v))
}

relVariData <- 
  dPrice %>% 
  calcTimeSeriesStats(
    c(varsPE, varsSE, varsFE), 
    stats = list("relative variation" = relativeVariation), 
    from = 2010)
```

### Summary

```{r}
summaryData <- 
  relVariData %>% 
  group_by(scenario) %>% 
  summarise(
    "Min." = min(value, na.rm=TRUE), 
    "1st Qu." = quantile(value, probs=0.25, na.rm=TRUE),
    "Median" = median(value, na.rm=TRUE),
    "Mean" = mean(value, na.rm=TRUE),
    "3rd Qu." = quantile(value, probs=0.75, na.rm=TRUE),
    "Max." = max(value, na.rm=TRUE))

summaryData %>% 
  kbl(
    caption = "Overall Relative Variation Summary of Prices",
    booktabs = TRUE
  ) %>%
  kable_styling(
    bootstrap_options = c("striped", "condensed"),
    latex_options = c("striped", "hold_position"),
    full_width = FALSE
  )
```

### By Variable

```{r}
medianRV <- 
  relVariData %>% 
  group_by(scenario, variable) %>% 
  summarise(value = median(value, na.rm = TRUE)) %>% 
  pivot_wider(names_from = scenario, values_from = value)

medianRV %>% 
  kbl(
    caption = "Median Relative Variation of Prices over Regions",
    booktabs = TRUE
  ) %>%
  kable_styling(
    bootstrap_options = c("striped", "condensed"),
    latex_options = c("striped", "hold_position"),
    full_width = FALSE
  )
```

```{r}
quart3RV <- 
  relVariData %>% 
  group_by(scenario, variable) %>% 
  summarise(value = quantile(value, probs=0.75, na.rm=TRUE)) %>% 
  pivot_wider(names_from = scenario, values_from = value)

quart3RV %>% 
  kbl(
    caption = "3rd Quartile of Relative Variation of Prices over Regions",
    booktabs = TRUE
  ) %>%
  kable_styling(
    bootstrap_options = c("striped", "condensed"),
    latex_options = c("striped", "hold_position"),
    full_width = FALSE
  )
```

\newpage

### By Variable an Region

```{r}
showRelativeVariation <- function(relVariData, var) {
  d <- 
    relVariData %>% 
    filter(variable == var) %>% 
    select(scenario, region, value) %>% 
    pivot_wider(names_from = region, values_from = value)
  d %>% 
    kbl(
      caption = paste0(var, ": Relative Variation"),
      booktabs = TRUE
    ) %>%
    kable_styling(
      bootstrap_options = c("striped", "condensed"),
      latex_options = c("striped", "hold_position"),
      full_width = FALSE
    ) %>% 
    cat("\n\n")
}
```


#### PE Prices

```{r results='asis'}
walk(varsPE, showRelativeVariation, relVariData = relVariData)
```

\newpage

#### SE Prices


```{r results='asis'}
walk(varsSE, showRelativeVariation, relVariData = relVariData)
```

\newpage

#### FE Prices

```{r results='asis'}
walk(varsFE, showRelativeVariation, relVariData = relVariData)
``` 

\newpage


## Line Plots

### PE Prices

```{r}
walk(varsPE, showLinePlots, data = dPrice, scale = "fixed")
```

### SE Prices


```{r}
walk(varsSE, showLinePlots, data = dPrice, scale = "fixed")
```

### FE Prices

```{r}
walk(varsFE, showLinePlots, data = dPrice, scale = "fixed")
``` 
